[Settings]
  ID = "2bd1a695-425d-4fd8-8e75-f061dcb69f37"

[Build]
  Publish = ""
  Functions = ""

[[redirects]]
  from = "/products/*"
  to = "/manufacturers/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/lines/*"
  to = "/lines/:splat"
  status = 301
  force = false
